baseURL = 'https://fryrvo.com'
languageCode = 'en-us'
title = 'Fryrvo Fox'
theme = 'github-style'

[params]
  author = 'Fryrvo Fox'
  description = 't'
  github = 'Fryrvo'
  twitter = 'Fryrvo'
  location = 'Earth'
  avatar = 'https://github.com/Fryrvo.png'
